### ISSUE TITLE
Common_environment shoud allow users to modify before_*/after_* funcs

### ISSUE THREAD

**Issue by vrutkovs** [Containers-Testing-Framework/common-steps#4]
`from common_environment import before_all` is a bad idea: users can't perform actions in `before_*/after_*` funcs.

This should be replaced with `common_before_all` funcs, proper import and suggesting users to call those funcs in `environment.py`.

Other idea is to use a decorator for that

**Comment by rwngwn** [comment]
I think this issue can be closed now. because user now can use any hook in his custom environment.py files.

**Comment by thozza** [comment]
closing as per comment from @l-d-j
